# Generated by Django 3.2.3 on 2021-05-31 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(default='Book_Title', help_text='M_Title', max_length=20, verbose_name='Main Title')),
                ('book_ISBN', models.CharField(default='Book_ISBN', help_text='M_Title', max_length=20, verbose_name='Main Title')),
                ('book_page_num', models.CharField(default='Sheet_Page_Number', help_text='M_Title', max_length=20, verbose_name='Main Title')),
                ('book_edition', models.CharField(default='Book_Edition', help_text='M_Title', max_length=20, verbose_name='Main Title')),
                ('book_weight', models.CharField(default='Book_Weight', help_text='M_Title', max_length=20, verbose_name='Main Title')),
                ('boook_count', models.IntegerField(default='Book_Count', help_text='Book Cost', max_length=25, verbose_name='Cost')),
                ('boook_cost', models.FloatField(default='Book_Cost', help_text='Book Cost', max_length=25, verbose_name='Cost')),
                ('is_available', models.BooleanField(default=True)),
                ('pub_date', models.DateField(verbose_name='Pub date')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_company_title', models.CharField(default='Book_Title', help_text='M_Title', max_length=20, verbose_name='Main Title')),
                ('delivery_company_phone', models.CharField(default='Book_ISBN', help_text='M_Title', max_length=20, verbose_name='Main Title')),
                ('delivery_cost', models.FloatField(default='Book_Cost', help_text='Book Cost', max_length=25, verbose_name='Cost')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_title', models.CharField(default='Book_Title', help_text='M_Title', max_length=20, verbose_name='Main Title')),
                ('publisher_phone', models.CharField(default='Book_ISBN', help_text='M_Title', max_length=20, verbose_name='Main Title')),
                ('publisher_address', models.CharField(default='Sheet_Page_Number', help_text='M_Title', max_length=20, verbose_name='Main Title')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default='Book_Cost', help_text='Book Cost', max_length=25, verbose_name='Cost')),
                ('book', models.ManyToManyField(to='api.Book')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default='Book_Title', help_text='M_Title', max_length=20, verbose_name='Main Title')),
                ('total_cost', models.FloatField(default='Book_Cost', help_text='Book Cost', max_length=25, verbose_name='Cost')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ManyToManyField(to='api.Book')),
                ('delivery_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.deliverycompany')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_title', models.CharField(default='Book_Title', help_text='M_Title', max_length=20, verbose_name='Main Title')),
                ('book', models.ManyToManyField(to='api.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.CharField(default='Book_Title', help_text='M_Title', max_length=3000, verbose_name='Main Title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.publisher'),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_number', models.CharField(default='Book_Title', help_text='M_Title', max_length=3000, verbose_name='Main Title')),
                ('book', models.ManyToManyField(to='api.Book')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(default='Book_Title', help_text='M_Title', max_length=20, verbose_name='Main Title')),
                ('author_second_name', models.CharField(default='Book_ISBN', help_text='M_Title', max_length=20, verbose_name='Main Title')),
                ('author_third_name', models.CharField(default='Sheet_Page_Number', help_text='M_Title', max_length=20, verbose_name='Main Title')),
                ('book', models.ManyToManyField(to='api.Book')),
            ],
        ),
    ]
