# Generated by Django 3.2.3 on 2021-05-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_ISBN',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='boook_cost',
        ),
        migrations.RemoveField(
            model_name='book',
            name='boook_count',
        ),
        migrations.AddField(
            model_name='book',
            name='NULL',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Book ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_cost',
            field=models.FloatField(default=0, max_length=25, verbose_name='Book Cost'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_count',
            field=models.IntegerField(default=0, max_length=25, verbose_name='Book Count'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_first_name',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Author First Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_second_name',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Author Second Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_third_name',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Author Third Name'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='basket_number',
            field=models.CharField(default='NULL', max_length=3000, verbose_name='Basket Number'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_edition',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Book Edition'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_page_num',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Book Page Number'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_weight',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Book Weight'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Is Available'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='delivery_company_phone',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Delivery Company Phone'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='delivery_company_title',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Delivery Company Title'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='delivery_cost',
            field=models.FloatField(default=0, max_length=25, verbose_name='Delivery Cost'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.CharField(default='NULL', max_length=3000, verbose_name='Feedback Text'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_title',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Genre Title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed on'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is Completed'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(default=0, max_length=25, verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_address',
            field=models.CharField(default='Publisher_Address', max_length=20, verbose_name='Publisher Address'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_phone',
            field=models.CharField(default='Publisher_Phone', max_length=20, verbose_name='Publisher Phone'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_title',
            field=models.CharField(default='Publisher_Title', max_length=20, verbose_name='Publisher Title'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0, max_length=25, verbose_name='Rating'),
        ),
    ]
