# Generated by Django 3.2.3 on 2021-05-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210531_0712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='deliverycompany',
            options={'verbose_name': 'Доставщик', 'verbose_name_plural': 'Доставщики'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Издательство', 'verbose_name_plural': 'Издательства'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterField(
            model_name='author',
            name='author_first_name',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_second_name',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_third_name',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='basket_number',
            field=models.CharField(default='NULL', max_length=3000, verbose_name='Номер Корзины'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_ISBN',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Номер ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cost',
            field=models.FloatField(default=0, verbose_name='Стоимость книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_count',
            field=models.IntegerField(default=0, verbose_name='Количество книг'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_edition',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Тираж'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_page_num',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_weight',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Вес, г'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='delivery_company_phone',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Номер Компании Доставки'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='delivery_company_title',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Название Компании Доставки'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='delivery_cost',
            field=models.FloatField(default=0, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.CharField(default='NULL', max_length=3000, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_title',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(default=0, verbose_name='Общая Стоимость'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_address',
            field=models.CharField(default='Publisher_Address', max_length=20, verbose_name='Адрес издательства'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_phone',
            field=models.CharField(default='Publisher_Phone', max_length=20, verbose_name='Номер издательства'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_title',
            field=models.CharField(default='Publisher_Title', max_length=20, verbose_name='Название издательства'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Оценка'),
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_cod', models.CharField(default='NULL', max_length=3000, verbose_name='Промо-код')),
                ('book', models.ManyToManyField(to='api.Book')),
            ],
            options={
                'verbose_name': 'Промо-код',
                'verbose_name_plural': 'Промо-коды',
            },
        ),
    ]
