version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - ./.envs/database/.postgres

  react:
    build:
      context: .
      dockerfile: ./compose/frontend/Dockerfile
    container_name: react
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: ["/start.sh"]

  django:
    build:
      context: .
      dockerfile: ./compose/backend/Dockerfile
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - react
    env_file:
      - ./.envs/database/.postgres
    command: ["/start.sh"]
